/**
 * Represents the different steps in the diagnostic process.
 */
export type Step = 'LOCATION' | 'VEHICLE' | 'QUESTIONS' | 'GENERATING' | 'REPORT' | 'HISTORY';

/**
 * Represents the state of the main form throughout the steps.
 */
export interface FormState {
  region: string;
  comuna: string;
  model: string;
  year: number;
  mileage: string;
  licensePlate?: string;
  issueType: string;
  q1: string;
  q2: string;
  q3: string;
  comments: string;
}

/**
 * Represents a required part for the repair.
 */
export interface Part {
  name: string;
  description: string;
  estimatedCost?: string;
}

/**
 * Represents a recommended service location (workshop or parts store).
 */
export interface ServiceLocation {
  name:string;
  address: string;
  phone?: string;
  reason?: string; // e.g., "Specializes in European cars"
}

/**
 * Represents the final diagnostic report generated by the AI.
 */
export interface Report {
  probableDiagnosis: string;
  repairInstructions: string[];
  requiredParts: Part[];
  recommendedWorkshops: ServiceLocation[];
  suggestedPartStores: ServiceLocation[];
}

/**
 * Represents a single item in the user's consultation history.
 */
export interface HistoryItem {
  id: string;
  formData: FormState;
  report: Report;
}
